[build]
target = "index.html"
dist = "dist"

[watch]
watch = ["src", "style", "index.html"]

[[hooks]]
stage = "pre_build"
command = "npx"
command_arguments = ["--yes", "tailwindcss", "-i", "style/input.css", "-o", "style/output.css", "--minify"]

[[proxy]]
backend = "https://june-pea-backend-production.up.railway.app:3000/api"
